syntax on
set encoding=UTF-8

""" Rest of the conf
source ~/.config/vim/config/binds.vim
source ~/.config/vim/config/lsp.vim
source ~/.config/vim/config/statusline.vim
source ~/.config/vim/config/filetree.vim
source ~/.config/vim/config/plugins.vim
source ~/.config/vim/config/writeonsave.vim

" set viminfofile local
set viminfofile=$XDG_STATE_HOME/vim/viminfo

" Line numbers
set number
set relativenumber

" tab shit
set tabstop=4       " Number of spaces a tab counts for
set shiftwidth=4    " Number of spaces for each step of autoindent
set expandtab       " Use spaces instead of tabs
set softtabstop=4   " Number of spaces tab key inserts/deletes

" color scheme
colorscheme wal

" white space
highlight RedundantSpaces ctermbg=red guibg=red
match RedundantSpaces /\s\+$\| \+\ze\t/
autocmd BufWritePre * %s/\s\+$//e

